server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_database?characterEncoding=utf-8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: ENC(OmqQbOji72uWuWZIdqL0aU+Npq0U2Kv/)
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
mybatis-plus:
  mapper-locations: classpath*:com/tipsy/repository/dao/*.xml
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
